import type { GlobalThemeOverrides } from 'naive-ui';

const fontFamily = "'Inter', -apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Segoe UI', sans-serif";

export const lightThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#6366f1',
    primaryColorHover: '#818cf8',
    primaryColorPressed: '#4f46e5',
    primaryColorSuppl: '#6366f1',
    successColor: '#10b981',
    warningColor: '#f59e0b',
    errorColor: '#ef4444',
    infoColor: '#6b7280',
    borderRadius: '8px',
    borderRadiusSmall: '6px',
    fontSize: '14px',
    fontSizeSmall: '12px',
    fontSizeMedium: '14px',
    fontSizeLarge: '16px',
    fontSizeHuge: '18px',
    fontFamily,
    bodyColor: '#f5f7fa',
    cardColor: '#ffffff',
    modalColor: '#ffffff',
    popoverColor: '#ffffff',
    tableColor: '#ffffff',
    inputColor: '#f5f7fa',
    actionColor: '#f1f5f9',
    hoverColor: '#f1f5f9',
    borderColor: '#e2e8f0',
    dividerColor: '#e2e8f0',
  },
  Button: {
    borderRadiusMedium: '8px',
    borderRadiusLarge: '10px',
    borderRadiusSmall: '6px',
    fontWeight: '500',
    fontSizeMedium: '14px',
    heightMedium: '36px',
    paddingMedium: '0 16px',
  },
  Card: {
    borderRadius: '12px',
    paddingMedium: '20px',
    paddingSmall: '16px',
    paddingLarge: '24px',
    borderColor: '#e2e8f0',
    color: '#ffffff',
    colorModal: '#ffffff',
    colorPopover: '#ffffff',
    colorEmbedded: '#f5f7fa',
    actionColor: '#f5f7fa',
  },
  Input: {
    borderRadius: '8px',
    heightMedium: '36px',
    fontSizeMedium: '14px',
    borderColorFocus: '#6366f1',
    boxShadowFocus: '0 0 0 2px rgba(99, 102, 241, 0.12)',
    borderHover: '1px solid #c7d2fe',
    colorFocus: '#ffffff',
  },
  Tag: {
    borderRadius: '6px',
    heightSmall: '22px',
    heightMedium: '28px',
    fontSizeSmall: '12px',
    fontSizeMedium: '13px',
  },
  Table: {
    borderRadius: '8px',
    thColor: '#f5f7fa',
    thTextColor: '#64748b',
    thFontWeight: '500',
    tdColor: '#ffffff',
    tdColorHover: '#f1f5f9',
    borderColor: '#e2e8f0',
    fontSize: '14px',
    lineHeight: '1.6',
  },
  Menu: {
    borderRadius: '6px',
    itemHeight: '40px',
    itemFontSize: '14px',
    itemFontWeight: '500',
    itemColorActive: '#6366f1',
    itemColorActiveHover: '#818cf8',
    itemTextColorActive: '#6366f1',
    itemTextColorActiveHover: '#4f46e5',
    itemIconColorActive: '#6366f1',
    itemIconColorActiveHover: '#4f46e5',
    itemColorHover: '#f1f5f9',
    itemTextColorHover: '#0f172a',
    itemIconColorHover: '#64748b',
    itemColor: 'transparent',
    itemTextColor: '#64748b',
    itemIconColor: '#94a3b8',
    itemColorChildActive: '#f1f5f9',
    itemTextColorChildActive: '#6366f1',
    itemIconColorChildActive: '#6366f1',
    groupTextColor: '#94a3b8',
    groupFontSize: '12px',
  },
  DataTable: {
    borderRadius: '8px',
    thColor: '#f5f7fa',
    thTextColor: '#64748b',
    thFontWeight: '500',
    tdColor: '#ffffff',
    tdColorHover: '#f1f5f9',
    borderColor: '#e2e8f0',
    fontSize: '14px',
    lineHeight: '1.6',
  },
  Modal: {
    borderRadius: '12px',
    fontSize: '14px',
  },
  Select: {
    borderRadius: '8px',
    peers: {
      InternalSelection: {
        borderRadius: '8px',
        heightMedium: '36px',
      },
    },
  },
  Form: {
    labelFontSizeTopMedium: '14px',
    labelFontWeight: '500',
  },
};

export const darkThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#818cf8',
    primaryColorHover: '#a5b4fc',
    primaryColorPressed: '#6366f1',
    primaryColorSuppl: '#818cf8',
    successColor: '#34d399',
    warningColor: '#fbbf24',
    errorColor: '#f87171',
    infoColor: '#9ca3af',
    borderRadius: '8px',
    borderRadiusSmall: '6px',
    fontSize: '14px',
    fontSizeSmall: '12px',
    fontSizeMedium: '14px',
    fontSizeLarge: '16px',
    fontSizeHuge: '18px',
    fontFamily,
    bodyColor: '#0c1222',
    cardColor: '#1a2332',
    modalColor: '#1a2332',
    popoverColor: '#1a2332',
    tableColor: '#1a2332',
    inputColor: '#162030',
    actionColor: '#162030',
    hoverColor: '#2d3a4d',
    borderColor: '#2d3a4d',
    dividerColor: '#2d3a4d',
  },
  Button: {
    borderRadiusMedium: '8px',
    borderRadiusLarge: '10px',
    borderRadiusSmall: '6px',
    fontWeight: '500',
    fontSizeMedium: '14px',
    heightMedium: '36px',
    paddingMedium: '0 16px',
  },
  Card: {
    borderRadius: '12px',
    paddingMedium: '20px',
    paddingSmall: '16px',
    paddingLarge: '24px',
    borderColor: '#2d3a4d',
    color: '#1a2332',
    colorModal: '#1a2332',
    colorPopover: '#1a2332',
    colorEmbedded: '#162030',
    actionColor: '#162030',
  },
  Input: {
    borderRadius: '8px',
    heightMedium: '36px',
    fontSizeMedium: '14px',
    borderColorFocus: '#818cf8',
    boxShadowFocus: '0 0 0 2px rgba(129, 140, 248, 0.15)',
    borderHover: '1px solid #3d4f63',
    colorFocus: '#1a2332',
  },
  Tag: {
    borderRadius: '6px',
    heightSmall: '22px',
    heightMedium: '28px',
    fontSizeSmall: '12px',
    fontSizeMedium: '13px',
  },
  Table: {
    borderRadius: '8px',
    thColor: '#162030',
    thTextColor: '#94a3b8',
    thFontWeight: '500',
    tdColor: '#1a2332',
    tdColorHover: '#2d3a4d',
    borderColor: '#2d3a4d',
    fontSize: '14px',
    lineHeight: '1.6',
  },
  Menu: {
    borderRadius: '6px',
    itemHeight: '40px',
    itemFontSize: '14px',
    itemFontWeight: '500',
    itemColorActive: 'rgba(129, 140, 248, 0.1)',
    itemColorActiveHover: 'rgba(129, 140, 248, 0.15)',
    itemTextColorActive: '#818cf8',
    itemTextColorActiveHover: '#a5b4fc',
    itemIconColorActive: '#818cf8',
    itemIconColorActiveHover: '#a5b4fc',
    itemColorHover: '#2d3a4d',
    itemTextColorHover: '#f1f5f9',
    itemIconColorHover: '#94a3b8',
    itemColor: 'transparent',
    itemTextColor: '#94a3b8',
    itemIconColor: '#64748b',
    itemColorChildActive: '#2d3a4d',
    itemTextColorChildActive: '#818cf8',
    itemIconColorChildActive: '#818cf8',
    groupTextColor: '#64748b',
    groupFontSize: '12px',
  },
  DataTable: {
    borderRadius: '8px',
    thColor: '#162030',
    thTextColor: '#94a3b8',
    thFontWeight: '500',
    tdColor: '#1a2332',
    tdColorHover: '#2d3a4d',
    borderColor: '#2d3a4d',
    fontSize: '14px',
    lineHeight: '1.6',
  },
  Modal: {
    borderRadius: '12px',
    fontSize: '14px',
  },
  Select: {
    borderRadius: '8px',
    peers: {
      InternalSelection: {
        borderRadius: '8px',
        heightMedium: '36px',
      },
    },
  },
  Form: {
    labelFontSizeTopMedium: '14px',
    labelFontWeight: '500',
  },
};

export const homehubThemeOverrides = lightThemeOverrides;
